In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("/Users/pablopadres/Documents/School/MS2/thesis/Data/raw_data/human_rights_risk_&_responsiveness.xlsx")

df.head()

,Brand,HRD_Attacks,Other_Allegations,Response_Requests,Response_Rate
0,GAP,3,10,25,96
1,Banana Republic,3,10,25,96
2,Old Navy,0,0,2,50
3,American Eagle,0,6,7,72
4,Abercrombie & Fitch,0,0,3,67

In [3]:
df.columns = df.columns.str.strip().str.replace(" ", "_")

df.columns

Index(['Brand', 'HRD_Attacks', 'Other_Allegations', 'Response_Requests',
       'Response_Rate'],
      dtype='object')

In [4]:
HRD_POINTS = 35
OTHER_POINTS = 20
REQUEST_POINTS = 20
RESPONSE_POINTS = 25

In [8]:
max_hrd = df["HRD_Attacks"].max()
max_other = df["Other_Allegations"].max()
max_requests = df["Response_Requests"].max()
max_response = 100

max_hrd, max_other, max_requests

(np.int64(3), np.int64(27), np.int64(25))

In [9]:
df["hrd_deduction"] = (df["HRD_Attacks"] / max_hrd) * HRD_POINTS
df["other_allegations_deduction"] = (df["Other_Allegations"] / max_other) * OTHER_POINTS
df["response_requests_deduction"] = (df["Response_Requests"] / max_requests) * REQUEST_POINTS

In [10]:
df["response_rate_deduction"] = ((max_response - df["Response_Rate"]) / max_response) * RESPONSE_POINTS

In [11]:
df["HRRR_score"] = (
    100
    - df["hrd_deduction"]
    - df["other_allegations_deduction"]
    - df["response_requests_deduction"]
    - df["response_rate_deduction"]
)

In [14]:
df["HRRR_score"] = df["HRRR_score"].clip(lower=0).round(2)

df[[
    "Brand",
    "HRD_Attacks",
    "Other_Allegations",
    "Response_Requests",
    "Response_Rate",
    "HRRR_score"
]]

,Brand,HRD_Attacks,Other_Allegations,Response_Requests,Response_Rate,HRRR_score
0,GAP,3,10,25,96,36.59
1,Banana Republic,3,10,25,96,36.59
2,Old Navy,0,0,2,50,85.90
3,American Eagle,0,6,7,72,82.96
4,Abercrombie & Fitch,0,0,3,67,89.35
5,Nike,0,27,20,85,60.25
6,Under Armour,0,17,6,50,70.11
7,Lululemon,0,7,5,80,85.81
8,New Balance,0,2,5,0,69.52
9,Champion,1,11,15,80,63.19
10,Levi Strauss & Co.,0,10,4,25,70.64
11,Wrangler,1,10,8,50,62.03
12,Ralph Lauren Corporation,0,0,1,100,99.20
13,Tommy Hilfiger,1,0,1,100,87.53
14,Clavin Klein,0,5,5,40,77.30
15,Michael Kors,1,3,6,34,64.81
16,COACH,0,0,1,0,74.20
17,Kate Spade,0,5,0,60,86.30
18,Converse,0,0,2,100,98.40
19,Hanes,0,1,3,100,96.86
20,Victoria's Secret,0,2,2,100,96.92
21,The North Face,0,2,5,0,69.52
22,Forever 21,0,0,2,0,73.40
23,Tory Burch,0,2,3,100,96.12
24,Fruit of the Loom,0,0,0,100,100.00
25,Patagonia,0,0,5,60,86.00
26,Marc Jacobs,0,0,0,100,100.00
27,Tom Ford,0,2,2,0,71.92
28,Urban Outfitters,0,2,2,0,71.92
29,Anthropologie,0,0,0,100,100.00
30,Steve Madden,0,1,0,0,74.26
31,LL Bean,0,1,0,0,74.26

In [13]:
df.columns

Index(['Brand', 'HRD_Attacks', 'Other_Allegations', 'Response_Requests',
       'Response_Rate', 'hrd_deduction', 'other_allegations_deduction',
       'response_requests_deduction', 'response_rate_deduction', 'HRRR_score'],
      dtype='object')